/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Project {
  'id' : ProjectId,
  'owner' : Principal,
  'name' : string,
  'createdAt' : Time,
  'publishStatus' : { 'published' : null } |
    { 'draft' : null },
  'description' : [] | [string],
  'updatedAt' : Time,
  'state' : ProjectState,
  'urlSlug' : [] | [string],
}
export type ProjectId = bigint;
export interface ProjectState {
  'lastEdited' : Time,
  'theme' : Theme,
  'title' : string,
  'tagline' : string,
  'body' : string,
}
export type Theme = { 'custom' : null } |
  { 'dark' : null } |
  { 'light' : null };
export type Time = bigint;
export interface UserProfile { 'name' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'createProject' : ActorMethod<[string, [] | [string]], ProjectId>,
  'deleteProject' : ActorMethod<[ProjectId], undefined>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getProject' : ActorMethod<[ProjectId], Project>,
  'getProjectPublic' : ActorMethod<[ProjectId], Project>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'getUserProjects' : ActorMethod<[Principal], Array<Project>>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'listPublicProjects' : ActorMethod<[], Array<Project>>,
  'publishProject' : ActorMethod<[ProjectId], undefined>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'saveProjectState' : ActorMethod<
    [ProjectId, string, string, string, Theme],
    undefined
  >,
  'unpublishProject' : ActorMethod<[ProjectId], undefined>,
  'updateProject' : ActorMethod<[ProjectId, string, [] | [string]], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];