/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const ProjectId = IDL.Nat;
export const UserProfile = IDL.Record({ 'name' : IDL.Text });
export const Time = IDL.Int;
export const Theme = IDL.Variant({
  'custom' : IDL.Null,
  'dark' : IDL.Null,
  'light' : IDL.Null,
});
export const ProjectState = IDL.Record({
  'lastEdited' : Time,
  'theme' : Theme,
  'title' : IDL.Text,
  'tagline' : IDL.Text,
  'body' : IDL.Text,
});
export const Project = IDL.Record({
  'id' : ProjectId,
  'owner' : IDL.Principal,
  'name' : IDL.Text,
  'createdAt' : Time,
  'publishStatus' : IDL.Variant({ 'published' : IDL.Null, 'draft' : IDL.Null }),
  'description' : IDL.Opt(IDL.Text),
  'updatedAt' : Time,
  'state' : ProjectState,
  'urlSlug' : IDL.Opt(IDL.Text),
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'createProject' : IDL.Func([IDL.Text, IDL.Opt(IDL.Text)], [ProjectId], []),
  'deleteProject' : IDL.Func([ProjectId], [], []),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getProject' : IDL.Func([ProjectId], [Project], ['query']),
  'getProjectPublic' : IDL.Func([ProjectId], [Project], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'getUserProjects' : IDL.Func([IDL.Principal], [IDL.Vec(Project)], ['query']),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'listPublicProjects' : IDL.Func([], [IDL.Vec(Project)], ['query']),
  'publishProject' : IDL.Func([ProjectId], [], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'saveProjectState' : IDL.Func(
      [ProjectId, IDL.Text, IDL.Text, IDL.Text, Theme],
      [],
      [],
    ),
  'unpublishProject' : IDL.Func([ProjectId], [], []),
  'updateProject' : IDL.Func([ProjectId, IDL.Text, IDL.Opt(IDL.Text)], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const ProjectId = IDL.Nat;
  const UserProfile = IDL.Record({ 'name' : IDL.Text });
  const Time = IDL.Int;
  const Theme = IDL.Variant({
    'custom' : IDL.Null,
    'dark' : IDL.Null,
    'light' : IDL.Null,
  });
  const ProjectState = IDL.Record({
    'lastEdited' : Time,
    'theme' : Theme,
    'title' : IDL.Text,
    'tagline' : IDL.Text,
    'body' : IDL.Text,
  });
  const Project = IDL.Record({
    'id' : ProjectId,
    'owner' : IDL.Principal,
    'name' : IDL.Text,
    'createdAt' : Time,
    'publishStatus' : IDL.Variant({
      'published' : IDL.Null,
      'draft' : IDL.Null,
    }),
    'description' : IDL.Opt(IDL.Text),
    'updatedAt' : Time,
    'state' : ProjectState,
    'urlSlug' : IDL.Opt(IDL.Text),
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'createProject' : IDL.Func([IDL.Text, IDL.Opt(IDL.Text)], [ProjectId], []),
    'deleteProject' : IDL.Func([ProjectId], [], []),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getProject' : IDL.Func([ProjectId], [Project], ['query']),
    'getProjectPublic' : IDL.Func([ProjectId], [Project], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'getUserProjects' : IDL.Func(
        [IDL.Principal],
        [IDL.Vec(Project)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'listPublicProjects' : IDL.Func([], [IDL.Vec(Project)], ['query']),
    'publishProject' : IDL.Func([ProjectId], [], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'saveProjectState' : IDL.Func(
        [ProjectId, IDL.Text, IDL.Text, IDL.Text, Theme],
        [],
        [],
      ),
    'unpublishProject' : IDL.Func([ProjectId], [], []),
    'updateProject' : IDL.Func(
        [ProjectId, IDL.Text, IDL.Opt(IDL.Text)],
        [],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };